### ISSUE TITLE
Apple clang error svmmarkers.cpp not found 

### ISSUE THREAD

**Issue by xliucs** [carlo-/aruco-ios-demo#5]
I always got these two errors while i am compiling the project: 

clang: error: no such file or directory: '/Users/xinliu/Google Drive/Gulp/ios app/aruco-ios-demo-master/Aruco/src/markerlabelers/svmmarkers.cpp'
clang: error: no input files

Could someone help me for this? Thanks!

**Comment by carlo-** [comment]
Which version of the Aruco library are you using? Unfortunately, version 3.0.X was removed from Aruco's official repository on Sourceforge, and that's the one supported by the app. If you downloaded it from there, then you're probably using version 3.1.X which won't work. You can try to use the 3.0.11 version from this mirror repository: [github.com/fnoop/aruco/tree/088a511f69d4df3c9518ebe1ce90a2590be8b4c8](https://github.com/fnoop/aruco/tree/088a511f69d4df3c9518ebe1ce90a2590be8b4c8) (make sure you download or clone the repository at this specific commit as linked).

I haven't checked the correctness of the code on the mirror repository so that's up to you. Let me know how it goes!

**Comment by xliucs** [comment]
Thanks so much Carlo! It worked! it would be great if you can add this to the readme file so that people would not get confused by the current link which only provides 3.1.X i beleive.

**Comment by carlo-** [comment]
I'm glad it worked! I will update the Readme. Thanks for the update.
